version: '3.9'
services:
   apache:
      image: galushko
#      image: php:8.1.2-apache
      ports:
         - 80:80
      volumes:
# только если пользователь в группе docker      
         - ${PWD}/www:/var/www/html
      depends_on:
         - mysql
   mysql:
#      image: mysql:latest
      build: ${PWD}/mysql
      ports:
         - 3306-3306
      environment:
         MYSQL_ROOT_PASSWORD: "secret1234"
         MYSQL_DATABASE: "miflib"
      volumes:
         - ${PWD}/dbData:/var/lib/mysql
#volumes:
#   - www:
#   - dbData:
