version: '3.9'
services:
# контейнер СЕРВЕРА БД
   db:
# собираем образ для сервера БД
      build: ./db
      container_name: db
      volumes:
         - ./init:/docker-entrypoint-initdb.d
#         - ./dbData:/var/lib/mysql
#         - ./init/init.sql:/data/application/init.sql
#      command: --init-file /data/application/init.sql
      ports:
         - '3306:3306'
      environment:
         MYSQL_ROOT_PASSWORD: "secret1234"
         MYSQL_DATABASE: "miflib"
#      restart: always
# Контейнер WEB СЕРВЕРА
   server:
      container_name: apache_server
      build: ./server
      ports:
         - '80:80'
      volumes:
         - ./www:/var/www/html
      depends_on:
         - db
# контенер КЛИЕНТ
   client:
      container_name: client
      build: ./client
      tty: true
      depends_on:
         - db
